config/routes.rb
Rails.application.routes.draw do
  root "vehicles#index"

  post 'filter', to: 'vehicles#filter', as: :vehicle_filter
  post 'import', to: 'vehicles#import', as: :vehicle_import
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/vehicle.rb
# frozen_string_literal: true

class Vehicle < ApplicationRecord
  SORTABLE_COLUMNS = %w[customer_full_name vehicle_type].freeze

  enum :vehicle_type, {
    bicycle: 'bicycle',
    campervan: 'campervan',
    motorboat: 'motorboat',
    rv: 'rv',
    sailboat: 'sailboat'
  }

  validates :customer_full_name, presence: true
  validates :customer_email, presence: true
  validates :vehicle_length, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :vehicle_name, presence: true, uniqueness: { case_sensitive: false, scope: %i[customer_email vehicle_type] }
  validates :vehicle_type, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vehicles_controller.rb
# frozen_string_literal: true

class VehiclesController < ApplicationController
  before_action :ensure_valid_filter_params, only: :filter
  before_action :ensure_file_presence, only: :import

  def index
    @vehicles = Vehicle.all
  end

  def import
    begin
      VehicleImporter.new(uploaded_file).import_vehicles

      flash[:success] = 'Import processed successfully!'
    rescue ActiveRecord::RecordInvalid => e
      flash[:danger] = "There was a problem processing your import. #{e.message}"
    end

    redirect_to action: :index
  end

  def filter
    @vehicles = Vehicle.all.order("#{params['column']} #{params['direction']}")

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('vehicle-rows', partial: 'vehicles/vehicles', locals: { vehicles: @vehicles })
      end
    end
  end

  private

  def ensure_file_presence
    unless uploaded_file.present?
      flash[:danger] = 'Please select a file before attempting to import new vehicles.'

      redirect_to action: :index
    end
  end

  def ensure_valid_filter_params
    unless params['column'].in?(Vehicle::SORTABLE_COLUMNS) && params['direction'].in?(%w[asc desc])
      flash[:danger] = 'Invalid filter parameters provided.'

      redirect_to action: :index
    end
  end

  def uploaded_file
    params['vehicle_import_file']&.tempfile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/delimiter_helper.rb
# frozen_string_literal: true

module DelimiterHelper
  def detect_delimiter(line)
    return '|' if line.include?('|')
    return ',' if line.include?(',')
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Outdoor.sy
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
    = favicon_link_tag asset_path('favicon.ico')
  %body
    - flash.each do |type, msg|
      %div{ class: "alert alert-#{type}"}
        = msg
    = yield

app/views/vehicles/_vehicle.html.haml
%tr.vehicles__table__rows__row
  %td
    = vehicle.customer_full_name
  %td
    = mail_to vehicle.customer_email
  %td
    = vehicle.vehicle_type
  %td
    = vehicle.vehicle_name
  %td.text-end
    = vehicle.vehicle_length
    = t('vehicles.index.unit_abbreviation')

app/views/vehicles/_vehicles.html.haml
%tbody#vehicle-rows
  = render @vehicles

app/views/vehicles/index.html.haml
.container-md.d-grid.gap-4
  .vehicles-header.text-center.pt-5
    = image_tag('logo.png', width: 250, alt: 'Outdoor.sy logo')
    .title.fs-4.my-2.fw-light
      = t('.customer_vehicles')

  .vehicles-import
    .fs-5.fw-light
      = t('.import_heading')

    .card.mt-2
      .card-body
        = form_with(url: vehicle_import_path, multipart: true ) do
          .file-import.d-flex.justify-content-between{ data: { controller: 'file-picker' } }
            = file_field_tag :vehicle_import_file, { accept: 'text/plain,text/csv', data: { 'file-picker-target': 'filePicker', action: 'file-picker#manageSubmitButton' } }
            = submit_tag t('.import_cta'), disabled: true, class: 'btn btn-sm btn-success', data: { 'file-picker-target': 'submitButton' }

  .vehicles-table
    .fs-5.fw-light
      = t('.table_heading')

    .card.mt-2{ data: { controller: 'sort' } }
      .card-body
        - if @vehicles.any?
          = form_with url: vehicle_filter_path, data: { 'sort-target': 'form' }, format: :turbo_stream do |f|
            = f.hidden_field :column, value: nil, data: { 'sort-target': 'column' }
            = f.hidden_field :direction, value: nil, data: { 'sort-target': 'direction' }
          %table.table.table-sm.table-borderless.table-fixed
            %thead
              %tr
                %th.sortable.name{ data: { 'sort-target': 'header', action: 'click->sort#applySort', column: :customer_full_name, direction: :asc, label: t('.headers.customer_name')} }
                  = t('.headers.customer_name')
                %th
                  = t('.headers.email')
                %th.sortable.type{ data: { 'sort-target': 'header', action: 'click->sort#applySort', column: :vehicle_type, direction: :asc, label: t('.headers.vehicle_type') } }
                  = t('.headers.vehicle_type')
                %th
                  = t('.headers.name')
                %th.text-end
                  = t('.headers.length')
            %tbody#vehicle-rows
              = render @vehicles
        - else
          %em= t('.none')